data:
  augmentation: null
  transform: efficientnetv2_pt
  batch_size: 256
  dataset: chest_xray
  num_classes: 2
logger:
  entity: atticux
  log_every_n_steps: 5
  mode: max
  monitor: val_best_f1
  project: medical-diagnosis
  run_name: efficient_v2_chest_xray
loss:
  alpha: null
  class_weights: null
  gamma: null
  name: cross_entropy
  reduction: mean
model:
  efficient_version: s
  name: Efficientnet_V2
  unfreeze_layers:
    - "classifier"
optimizer:
  lr: 0.1
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 6
  precision: null
