data:
  augmentation: null
  transform: resnet_pt
  batch_size: 256
  num_classes: 2
  dataset: chest_xray
logger:
  entity: atticux
  project: medical-diagnosis
  run_name: resnet18_chest_xray
model:
  name: resnet18
  unfreeze_layers:
    - fc

optimizer:
  lr: 0.1
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 6
  precision: null
