data:
  augmentation: null
  transform: resnet_pt
  batch_size: 256
  num_classes: 2
  dataset: chest_xray
logger:
  entity: atticux
  log_every_n_steps: 5
  mode: max
  monitor: val_best_f1
  project: medical-diagnosis
  run_name: test_run
loss:
  alpha: null
  class_weights: null
  gamma: null
  name: cross_entropy
  reduction: mean
model:
  name: resnet18
  unfreeze_layers:
    - fc

optimizer:
  lr: 0.1
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 8
  precision: null
