data:
  augmentation: null
  batch_size: 128
  data_dir: ./datasets
  dataset: chest_xray
  num_classes: 2
  transform: base
logger:
  entity: atticux
  project: medical-diagnosis
  run_name: test_run
loss:
  alpha: null
  class_weights: null
  gamma: null
  name: cross_entropy
  reduction: mean
model:
  efficient_version: null
  n_channels_1: null
  n_channels_2: null
  n_fc_1: null
  name: CNN
  unfreeze_layers: null
optimizer:
  lr: 0.0001
  name: adam
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 25
  precision: null
