data:
  augmentation: null
  transform: vit_pt
  batch_size: 512
  num_classes: 2
  dataset: chest_xray
logger:
  entity: atticux
  log_every_n_steps: 5
  mode: max
  monitor: val_best_f1
  project: medical-diagnosis
  run_name: vit_base_chest_xray
loss:
  alpha: null
  class_weights: null
  gamma: null
  name: cross_entropy
  reduction: mean
model:
  name: vit_base_patch16_224
  unfreeze_layers:
    - head

optimizer:
  lr: 0.01
  name: adamw
training:
  accumulate_grad_batches: null
  gradient_clip_val: null
  max_epochs: 10
  precision: null
